ALTER TABLE users ADD COLUMN status VARCHAR(50) DEFAULT 'ACTIVE' NOT NULL;
ALTER TABLE users ADD COLUMN last_successful_login_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN last_failed_login_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN failed_login_count INT DEFAULT 0 NOT NULL;
